env:
  browser: true
  es2021: true
  jquery: true
  greasemonkey: true
extends:
  - 'preact'
  - standard
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
settings:
  jest:
    version: 26
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    no-use-before-define: 0,
    semi: ['error', 'always'],
    no-undef: off,
    comma-dangle: ['error', 'always-multiline'],
    indent: off,
    '@typescript-eslint/indent': ['error', 2],
  }
