url: https://1ptba.com
host: 1ptba.com
siteType: NexusPHP
asSource: true
asTarget: true
uploadPath: /upload.php
seedDomSelector: '#top~table:first>tbody>tr:nth-child(5)' 
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
imdb:
  selector: 'input[name="url"][type="text"]'
anonymous: 
  selector: 'input[name="uplver"]'
category:
  selector: '#browsecat'
  map:
    movie: '401'
    tv: '402'
    tvPack: '402'
    documentary: '404'
    concert: '406'
    sport: '407'
    cartoon: '405'
    variety: '403'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '1'
    x264: '1'
    hevc: '10'
    x265: '10'
    h265: '10'
    mpeg2: '4'
    mpeg4: '1'
    vc1: '2'
    xvid: '3'
    dvd: '4'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '6'
    ac3: '18'
    dd: '18'
    dd+: '18'
    flac: '1'
    dts: '3'
    truehd: '20'
    lpcm: '21'
    dtshdma: '19'
    atmos: '19'
    dtsx: '3'
    ape: '2'
    wav: '22'
    mp3: '4'
    m4a: '5'
    other: '7'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '10'
    bluray: '13'
    remux: '3'
    encode: '7'
    web: '11'
    hdtv: '5'
    dvd: '2'
    dvdrip: '7'
    other: '12'
    cd: '8'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    4320p: '11'
    2160p: '10'
    1080p: '2'
    1080i: '2'
    720p: '4'
    576p: '5'
    480p: '5'
team: 
  selector: 'select[name="team_sel"]'
  map:
    1ptba: '1'
    chd: '2'
    mysilu: '3'
    wiki: '4'
    other: '5'