url: 'https://www.beitai.pt'
host: beitai.pt
siteType: NexusPHP
asSource: true
asTarget: false
seedDomSelector: '#top+table>tbody>tr:nth-child(3)'
uploadPath: /upload.php
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc