url: 'https://hdhome.org'
host: hdhome.org
siteType: NexusPHP
asSource: true
asTarget: true
uploadPath: /upload.php
seedDomSelector: '#top~table:first>tbody>tr:nth-child(5)' 
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
imdb:
  selector: 'input[name="url"][type="text"]'
douban:
  selector: 'input[name="douban_id"]'
anonymous: 
  selector: 'input[name="uplver"]'
tags: 
  chineseAudio: '#tag_gy'
  DIY: '#tag_diy'
  cantoneseAudio: '#tag_yy'
  chineseSubtitle: '#tag_zz'
  HDR: '#tag_hdr10'
  HDR10+: '#tag_hdrm'
  DolbyVision: '#tag_db'
category:
  selector: '#browsecat'
  map:
    movie:
      - '411'
      - '412'
      - '413'
      - '414'
      - '415'
      - '450'
      - '499'
      - '416'
    tv:
      - '425'
      - '426'
      - '471'
      - '427'
      - '428'
      - '429'
      - '430'
      - '452'
      - '431'
    tvPack:
      - '432'
      - '433'
      - '434'
      - '435'
      - '436'
      - '437'
      - '438'
      - '502'
    documentary:
      - '417'
      - '418'
      - '419'
      - '420'
      - '421'
      - '451'
      - '500'
      - '422'
    concert: '441'
    sport:
      - '442'
      - '443'
    cartoon:
      - '444'
      - '445'
      - '446'
      - '447'
      - '448'
      - '454'
      - '449'
      - '501'
    variety: []
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '1'
    hevc: '12'
    x264: '1'
    x265: '2'
    h265: '2'
    mpeg2: '4'
    mpeg4:
      - '5'
      - '412'
      - '418'
      - '426'
      - '433'
      - '445'
    vc1: '3'
    xvid: '5'
    dvd: '5'
source:
  selector: 'select[name="source_sel"]'
  map:
    uhdbluray: '9'
    bluray: '1'
    hdtv: '4'
    dvd: '3'
    web: '7'
    vhs: '8'
    hddvd: '8'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '6'
    ac3: '15'
    dd: '15'
    dd+: '15'
    dts: '3'
    truehd: '13'
    lpcm: '14'
    dtshdma: '11'
    atmos: '12'
    dtsx: '17'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray:
      - '10'
      - '499'
      - '500'
      - '502'
      - '501'
    bluray:
      - '1'
      - '450'
      - '451'
      - '452'
      - '453'
      - '454'
    remux:
      - '3'
      - '415'
      - '421'
      - '430'
      - '437'
      - '448'
    encode:
      - '7'
      - '411'
      - '412'
      - '413'
      - '414'
      - '416'
      - '417'
      - '418'
      - '419'
      - '420'
      - '422'
      - '425'
      - '426'
      - '471'
      - '427'
      - '428'
      - '429'
      - '431'
      - '432'
      - '433'
      - '434'
      - '435'
      - '436'
      - '438'
      - '444'
      - '445'
      - '446'
      - '447'
      - '449'
    web:
      - '11'
      - '411'
      - '412'
      - '413'
      - '414'
      - '416'
      - '417'
      - '418'
      - '419'
      - '420'
      - '422'
      - '425'
      - '426'
      - '471'
      - '427'
      - '429'
      - '431'
      - '432'
      - '433'
      - '434'
      - '436'
      - '438'
      - '444'
      - '445'
      - '446'
      - '447'
      - '449'
    hdtv:
      - '5'
      - '412'
      - '413'
      - '416'
      - '418'
      - '419'
      - '422'
      - '424'
      - '426'
      - '471'
      - '427'
      - '428'
      - '431'
      - '433'
      - '434'
      - '435'
      - '438'
      - '442'
      - '443'
      - '445'
      - '446'
      - '449'
    dvd:
      - ''
      - '411'
      - '417'
      - '425'
      - '432'
      - '444'
    dvdrip:
      - '7'
      - '411'
      - '417'
      - '425'
      - '432'
      - '444'
    other: ''
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    2160p:
      - '1'
      - '499'
      - '416'
      - '500'
      - '422'
      - '431'
      - '438'
      - '502'
      - '449'
      - '501'
    1080p:
      - '2'
      - '414'
      - '420'
      - '429'
      - '436'
      - '447'
    1080i:
      - '3'
      - '424'
      - '428'
      - '435'
      - '443'
    720p:
      - '4'
      - '413'
      - '419'
      - '423'
      - '427'
      - '434'
      - '442'
      - '446'
    576p:
      - '5'
      - '411'
      - '417'
      - '425'
      - '432'
      - '444'
    480p:
      - '5'
      - '411'
      - '417'
      - '425'
      - '432'
      - '444'
team: 
  selector: 'select[name="team_sel"]'
  map:
    hdhome: '1'
    hdh: '2'
    hdhtv: '3'
    hdhpad: '4'
    hdhweb: '12'
    3201: '20'
    shma: '17'
    tvman: '21'
    arin: '19'
    ttg: '6'
    mteam: '7'
    other: '11'
    969154968: '22'