url: 'https://pt.hdpost.top'
host: hdpost.top
siteType: UNIT3D
asSource: true
asTarget: true
uploadPath: /upload/1
needDoubanInfo: true
seedDomSelector: '#vue+.panel table>tbody>tr:last' 
search: 
  path: /torrents
  params:
    name: '{name}'
    imdb: '{imdb}'
name:
  selector: '#title'
description:
  selector: '#upload-form-description'
imdb:
  selector: '#autoimdb'
tmdb:
  selector: '#autotmdb'
mediaInfo:
  selector: 'textarea[name="mediainfo"]'
anonymous: 
  selector: '.radio-inline:first input[name="anonymous"]'
category:
  selector: '#browsecat'
  map:
    movie: '1'
    tv: '2'
    tvPack: '2'
videoType:
  selector: '#autotype'
  map:
    uhdbluray: '1'
    bluray: '1'
    remux: '2'
    encode: '3'
    web: '4'
    hdtv: '6'
    dvd: '1'
    dvdrip: '12'
    other: ''
resolution:
  selector: '#autores'
  map:
    4320p: '1'
    2160p: '2'
    1080p: '3'
    1080i: '4'
    720p: '5'
    576p: '6'
    480p: '8'