url: 'https://karagarga.in'
host: karagarga.in
siteType: KG
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAC0FBMVEUAAADMzMyDgIDBxMSAgIB6gID/4uIAgICAhYXNzc2IiIiXl5eDg4O/v7/BwcHAwMCFhYXGxsbS0tK5ubl7e3tzc3P////Ly8vMzMzMzMzMzMzMzMxvamqlpKSmpqZaWlqChYXP0tJ/gICChYVISUkTExMFBQWJh4fJycmDhYV+hYU9iIhXWloAhIQAgIDNzc3Q0NCsrKxVV1cdDg56OTk4OTkODQ1bAAA9REQAhYWSkpJfX18QEBB4eHiLi4uVlJSZmpqNjY15eXkODg5hYWEgICCIQEC9u7vBxMQ/Pz+CgoJGRkYVeXmuuLjq1NQAAAAZGRljXl5iqKi+v7/BwMBWVlaNjY2IiIiIiIhoaGihoaGMjIycoKCwsLDJw8PAwMC/v7/AwMDAwMCWlpaLi4uDg4PGxsbHx8fDw8PIyMiwsLDAwMDAwMDAwMDAwMC/v7+8vLzAwMDAwMC8vLy4uLi3t7eQkJCenp7BwcHAwMDAwMDAwMDBwcHBwcHPz8+NjY2Hh4eEhISnp6fBwcHAwMDAwMB7e3t7e3t7e3uqqqqHh4dhYWH8/Pyjo6N5eXmAgIB/f3+AgICbm5uKiorCwsLDw8OMjIy9vb3///////+JiYl/f39/f3+AgICwsLCioqK6urq/v7+amprw8PDMzMy/v7/AwMDExMR5eXmAgIDKysp/f3+AgICvr6+hoaG/v7++vr7BwcHAwMDExMR5eXmAgICpqakUFBQRQkIAAAABAABrJiYoQUEAHR0SERGKiopaW1sMBgZOHh4aCwsMAABKLS1OTk45OTlTUVEBDg4BYGAIISE9AAAJCQkDAwMODg4FBQUHBwcLCwsBAwMCDg5TAwNCOTk+Pj5bW1tZWVleXl4rKysWFxdYV1dcWVl3WFg7Ozs8PDxzc3PFxcW2trbAwMC4uLiHh4eIiIiMjIyPj4+zs7OdnZ2/v78GBgb///+lKbQMAAAAtnRSTlMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkTUEIDo3hNxoOBqD3++TnchSh7eSBAgFag32O8PCOfIhfJExJTMrhHQ6N+/v++sYaBp33vCADtuicX5oUv3t/dbruiNi6nO+WikT90FgtpehaxPfEwV7dRgKc9f786eDlxx0BHQkRkfleFR4aAwJ63elXD39/g4iIidzagX9/g1oB3Le5ubO3F6TuswxDUSMVTIEDAwMEBrawIHRE97mnD1YAAAABYktHRBZ80agZAAAAB3RJTUUH5QQMAwUgcVRTPQAAAThJREFUGNNjYKAaYJSQlJJmRBFiYpKR3SYnr6DIjBBjYVVSVtmuqqauwcYOF+TQ1NLesXPnrt06unpgAU59A0MjY5M9e/eZmplbWAIFuaysbWzt9h84eOjwkaP2DtwgVTyOTsecXVyPnzh56vQZN3cPXpCgp5f32XPnL1y8dPnK1Ws+vn58IEH/gOs3bty8dfvO3Xv3A4OCQ/hBgg8ehoaFh0dEPoqKjomNi09ITAIKJ6ekCggKpqU/zsjMevI0Oyc3DyiYXyDEwl9YVPyspLSsvKKyir8aKFhTy8cgLFxX//xFQ2NTc0srP8w3Im3tHS87u7pFYQI9vX39EyZOejV5ytRp02fMFAMLvn4za/acufPmty9YuOjt4iVLly1fsZLh3fNVYqvXrF3XJr5+w9uNm/Kfbt6yFQBipHYOvCm+yAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMS0wNC0xMlQwMzowNToyOCswMDowMNjzD2AAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjEtMDQtMTJUMDM6MDU6MjgrMDA6MDCprrfcAAAAAElFTkSuQmCC
asSource: true
asTarget: true
uploadPath: /upload.php
seedDomSelector: '.outer h1~table:first>tbody>tr:nth-child(6)'
torrentDownloadLinkSelector: 'a[href*="/down.php/"]'
needDoubanInfo: true
search:
  path: /browse.php
  imdbOptionKey: 'imdb'
  nameOptionKey: 'title'
  params:
    search: '{imdb}'
    search_type: '{optionKey}'
    sort: size
    d: DESC
source:
  selector: select[name='source']
  map:
    uhdbluray: Blu-ray
    bluray: Blu-ray
    hdtv: TV
    dvd: DVD
    web: WEB
    vhs: VHS
    hddvd: HD-DVD
    other: Other
resolution:
  selector: select[name='hdrip']
  map:
    720p: '1'
    1080p: '2'
    bluray: '3'
torrent:
  selector: 'input[name="file"]'
genres:
  map:
    Action: '4'
    Adventure: '55'
    Animation: '5'
    Arthouse: '6'
    Camp: '43'
    Classics: '8'
    Comedy: '9'
    Crime: '10'
    Cult: '11'
    Documentary: '20'
    Drama: '12'
    Epic: '44'
    Erotica: '13'
    Experimental: '51'
    Exploitation: '47'
    Fantasy: '14'
    Film Noir: '15'
    Giallo: '53'
    Horror: '17'
    Martial Arts: '18'
    Musical: '19'
    Mystery: '54'
    Performance: '60'
    Philosophy: '48'
    Politics: '49'
    Romance: '50'
    Sci-Fi: '21'
    Short: '22'
    Silent: '23'
    Thriller: '24'
    TV: '25'
    Video Art: '56'
    War: '26'
    Western: '27'
country:
  map:
    USA: '2'
    UK: '12'
    Germany: '7'
    Italy: '9'
    ---: '255'
    Abkhazia: '119'
    Afghanistan: '54'
    Akrotiri and Dhekelia: '120'
    Aland Islands: '121'
    Albania: '65'
    Algeria: '35'
    American Samoa: '122'
    Andorra: '68'
    Angola: '36'
    Anguilla: '123'
    Antigua Barbuda: '89'
    Argentina: '19'
    Armenia: '124'
    Aruba: '125'
    Ascension Island: '126'
    Australia: '20'
    Austria: '37'
    Azerbaijan: '118'
    Bahamas: '82'
    Bahrain: '127'
    Bangladesh: '86'
    Barbados: '85'
    Belarus: '129'
    Belgium: '16'
    Belize: '34'
    Benin: '116'
    Bermuda: '130'
    Bhutan: '131'
    Bolivia: '132'
    Bosnia Herzegovina: '67'
    Botswana: '133'
    Brazil: '18'
    British Virgin Islands: '134'
    Brunei: '135'
    Bulgaria: '104'
    Burkina Faso: '60'
    Burundi: '136'
    Cambodia: '84'
    Cameroon: '137'
    Canada: '5'
    Cape Verde: '138'
    Cayman Islands: '139'
    Central African Republic: '140'
    Chad: '114'
    Chile: '51'
    China: '8'
    Christmas Island: '141'
    Cocos (Keeling) Islands: '142'
    Colombia: '99'
    Comoros: '143'
    Congo (Brazzaville): '53'
    Congo-Kinshasa (Zaire): '252'
    Cook Islands: '144'
    Costa Rica: '102'
    Cote d'Ivoire: '145'
    Croatia: '97'
    Cuba: '52'
    Cyprus: '146'
    Czech Republic: '46'
    Denmark: '10'
    Djibouti: '147'
    Dominica: '148'
    Dominican Republic: '41'
    Ecuador: '81'
    Egypt: '103'
    El Salvador: '149'
    Equatorial Guinea: '150'
    Eritrea: '151'
    Estonia: '98'
    Ethiopia: '112'
    European Union: '253'
    Falkland Islands: '153'
    Faroe Islands: '111'
    Fiji: '152'
    Finland: '4'
    France: '6'
    French Polynesia: '154'
    Gabon: '155'
    Gambia: '156'
    Georgia: '108'
    Ghana: '157'
    Gibraltar: '158'
    Greece: '42'
    Greenland: '159'
    Grenada: '160'
    Guam: '161'
    Guatemala: '43'
    Guernsey: '162'
    Guinea: '113'
    Guinea-Bissau: '163'
    Guyana: '164'
    Haiti: '165'
    Honduras: '79'
    Hong Kong: '33'
    Hungary: '74'
    Iceland: '62'
    India: '70'
    Indonesia: '166'
    Iran: '107'
    Iraq: '167'
    Ireland: '13'
    Isla de Muerte: '105'
    Isle of Man: '168'
    Israel: '44'
    Jamaica: '31'
    Japan: '17'
    Jersey: '170'
    Jordan: '169'
    Kazakhstan: '110'
    Kenya: '172'
    Kiribati: '58'
    Kosovo: '173'
    Kuwait: '171'
    Kyrgyzstan: '80'
    Laos: '87'
    Latvia: '101'
    Lebanon: '100'
    Lesotho: '174'
    Liberia: '175'
    Libya: '176'
    Liechtenstein: '177'
    Lithuania: '69'
    Luxembourg: '32'
    Macau: '178'
    Macedonia: '179'
    Madagascar: '180'
    Malawi: '181'
    Malaysia: '40'
    Maldives: '182'
    Mali: '115'
    Malta: '183'
    Marshall Islands: '184'
    Mauritania: '185'
    Mauritius: '186'
    Mayotte: '187'
    Mexico: '25'
    Micronesia: '188'
    Moldova: '189'
    Monaco: '190'
    Mongolia: '109'
    Montenegro: '257'
    Montserrat: '191'
    Morocco: '192'
    Mozambique: '193'
    Myanmar: '194'
    Nagorno-Karabakh: '195'
    Namibia: '196'
    Nauru: '63'
    Nepal: '197'
    Netherlands: '15'
    Netherlands Antilles: '71'
    New Caledonia: '198'
    New Zealand: '21'
    Nicaragua: '199'
    Niger: '200'
    Nigeria: '61'
    Niue: '201'
    Norfolk Island: '202'
    North Korea: '96'
    Northern Cyprus: '203'
    Northern Mariana Islands: '204'
    Norway: '11'
    Oman: '205'
    Pakistan: '45'
    Palau: '207'
    Palestine: '208'
    Panama: '206'
    Papua New Guinea: '209'
    Paraguay: '90'
    Peru: '83'
    Philippines: '59'
    Pitcairn Islands: '210'
    Poland: '14'
    Portugal: '24'
    Puerto Rico: '50'
    Qatar: '211'
    Romania: '75'
    Russia: '3'
    Rwanda: '212'
    Saint Helena: '213'
    Saint Kitts and Nevis: '214'
    Saint Lucia: '215'
    Saint Vincent and the Grenadines: '217'
    Saint-Pierre and Miquelon: '216'
    Samoa: '39'
    San Marino: '219'
    São Tomé and Príncipe: '220'
    Saudi Arabia: '221'
    Sealand: '258'
    Senegal: '94'
    Serbia: '256'
    Serbia and Montenegro: '47'
    Seychelles: '48'
    Sierra Leone: '222'
    Singapore: '26'
    Slovakia: '223'
    Slovenia: '64'
    Solomon Islands: '224'
    Somalia: '225'
    Somaliland: '226'
    South Africa: '29'
    South Korea: '30'
    South Ossetia: '227'
    Spain: '23'
    Sri Lanka: '228'
    Sudan: '229'
    Suriname: '230'
    Svalbard: '231'
    Swaziland: '232'
    Sweden: '1'
    Switzerland: '57'
    Syria: '233'
    Taiwan: '49'
    Tajikistan: '234'
    Tanzania: '235'
    Thailand: '93'
    Timor-Leste: '236'
    Togo: '95'
    Tokelau: '237'
    Tonga: '238'
    Transnistria: '239'
    Trinidad & Tobago: '78'
    Tristan da Cunha: '240'
    Tunisia: '106'
    Turkey: '55'
    Turkmenistan: '66'
    Turks and Caicos Islands: '241'
    Tuvalu: '242'
    Uganda: '243'
    Ukraine: '72'
    United Arab Emirates: '244'
    United Kingdom: '12'
    Uruguay: '88'
    USSR: '92'
    Uzbekistan: '56'
    Vanuatu: '76'
    Various/International: '117'
    Vatican City: '245'
    Venezuela: '73'
    Vietnam: '77'
    Virgin Islands: '246'
    Wallis and Futuna: '247'
    Western Sahara: '248'
    World: '254'
    Yemen: '249'
    Yugoslavia: '38'
    Zambia: '250'
    Zimbabwe: '251'
