url: 'https://karagarga.in'
host: karagarga.in
siteType: KG
asSource: true
asTarget: false
uploadPath: /upload.php
seedDomSelector: '.outer h1~table:first>tbody>tr:nth-child(6)'
needDoubanInfo: true
search: 
  path: /browse.php
  imdbOptionKey: 'imdb'
  nameOptionKey: 'title'
  params:
    search: '{imdb}'
    search_type: '{optionKey}'
    sort: size
    d: DESC