url: 'https://lemonhd.org'
host: lemonhd.org
siteType: NexusPHP
asSource: true
asTarget: true
seedDomSelector: '#top~table:first>tbody>tr:nth-child(5)'
uploadPath: /upload_movie.php
search: 
  path: /torrents.php
  imdbOptionKey: 'imdb'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
imdb:
  selector: 'input[name="url"][type="text"]'
douban: 
  selector: 'input[name="douban_url"]'
tags: 
  chineseAudio: 'input[name="tag_gy"]'
  DIY: '#tagDIY'
  cantoneseAudio: 'input[name="tag_yy"]'
  chineseSubtitle: 'input[name="tag_zz"]'
  CC: 'input[name="tag_cc"]'
category:
  selector: '#browsecat'
  map:
    movie: '401'
    tv: '402'
    tvPack: '402'
    documentary: '404'
    concert: '406'
    variety: '403'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '1'
    hevc: '10'
    x264: '12'
    x265: '11'
    h265: '10'
    mpeg2: '4'
    mpeg4: '1'
    vc1: '2'
    xvid: '3'
    dvd: '4'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '8'
    ac3: '14'
    dd: '14'
    dd+: '14'
    flac: '7'
    dts: '6'
    truehd: '2'
    lpcm: '15'
    dtshdma: '5'
    atmos: '1'
    dtsx: '4'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '9'
    bluray: '1'
    remux: '3'
    encode: '7'
    web: '11'
    hdtv: '5'
    dvd: '6'
    dvdrip: '7'
    hddvd: '2'
    other: '4'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    4320p: '6'
    2160p: '1'
    1080p: '2'
    1080i: '2'
    720p: '4'
    576p: '5'
    480p: '5'
area:
  selector: 'select[name="processing_sel"]'
  map:
    CN: '1'
    US: '3'
    EU: '3'
    HK: '2'
    TW: '2'
    JP: '4'
    KR: '4'
    OT: '5'