url: 'https://kp.m-team.cc'
host: m-team.cc
siteType: NexusPHP
asSource: true
asTarget: true
uploadPath: /upload.php
seedDomSelector: '#top~table:first>tbody>tr:nth-child(6)' 
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
imdb:
  selector: 'input[name="url"][type="text"]'
tags: 
  chineseAudio: '#l_dub'
  DIY: '#l_diy'
  chineseSubtitle: '#l_sub'
category:
  selector: '#browsecat'
  map:
    movie:
      - '401'
      - '419'
      - '420'
      - '421'
      - '439'
    tv:
      - '403'
      - '402'
      - '435'
      - '438'
    tvPack:
      - '403'
      - '402'
      - '435'
      - '438'
    documentary: '404'
    concert: '406'
    sport: '407'
    cartoon: '405'
    app: '422'
    ebook: '427'
    magazine: '427'
    audioBook: '427'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '1'
    hevc: '16'
    h265: '16'
    x264: '1'
    x265: '16'
    mpeg2: '4'
    mpeg4: '15'
    vc1: '2'
    xvid: '3'
videoType:
  map:
    uhdbluray:
      - '421'
      - '438'
    bluray:
      - '421'
      - '438'
    remux: '439'
    encode:
      - '401'
      - '419'
      - '403'
      - '402'
    web:
      - '419'
      - '402'
    hdtv:
      - '419'
      - '402'
    dvd:
      - '420'
      - '435'
    dvdrip:
      - '401'
      - '403'
    other: ''
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    2160p:
      - '6'
      - '419'
      - '402'
    1080p:
      - '1'
      - '419'
      - '402'
    1080i:
      - '2'
      - '419'
      - '402'
    720p:
      - '3'
      - '419'
      - '402'
    576p:
      - '5'
      - '401'
      - '403'
    480p:
      - '5'
      - '401'
      - '403'
area:
  selector: 'select[name="processing_sel"]'
  map:
    CN: '1'
    US: '2'
    EU: '2'
    HK: '3'
    TW: '3'
    JP: '4'
    KR: '5'
    OT: '6'
team: 
  selector: 'select[name="team_sel"]'
  map:
    mteam: '9'
    mpad: '10'
    tnp: '23'
    mteamtv: '17'
    kishd: '7'
    bmdru: '6'
    onehd: '18'
    cnhk: '19'
    stbox: '20'
    r2hd: '21'
    pack: '8'
    geek: '24'