url: 'https://ourbits.club'
host: ourbits.club
siteType: NexusPHP
asSource: true
asTarget: true
seedDomSelector: '#top~table:first>tbody>tr:nth-child(3)' 
uploadPath: /upload.php
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
name:
  selector: 'input[name="name"]'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
poster: 'input[name="picture"]'
imdb:
  selector:  'input[name="url"][type="text"]'
anonymous: 
  selector: 'input[name="uplver"]'
tags: 
  chineseAudio: '#tagGY'
  DIY: '#tagDIY'
  cantoneseAudio: '#tag_yy'
  chineseSubtitle: '#tagZZ'
  HDR: '#tagHDR10'
  HDR10+: '#tagHDR10P'
  DolbyVision: '#tagDB'
category:
  selector: 'select[name="type"]'
  map:
    movie: '401'
    3d: '402'
    tv: '412'
    tvPack: '405'
    documentary: '410'
    concert: '419'
    sport: '415'
    cartoon: '411'
    variety: '413'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '12'
    hevc: '14'
    x264: '12'
    x265: '14'
    h265: '14'
    mpeg2: '15'
    mpeg4: '12'
    vc1: '16'
    xvid: '17'
    dvd: '18'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '7'
    ac3: '6'
    dd: '6'
    dd+: '6'
    flac: '13'
    dts: '4'
    truehd: '2'
    lpcm: '5'
    dtshdma: '1'
    atmos: '14'
    dtsx: '21'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '12'
    bluray: '1'
    remux: '4'
    encode: '7'
    web: '9'
    hdtv: '5'
    dvd: '2'
    dvdrip: '2'
    other: '0'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    2160p: '5'
    1080p: '1'
    1080i: '2'
    720p: '3'
    576p: '4'
    480p: '4'
area:
  selector: 'select[name="processing_sel"]'
  map:
    CN: '1'
    US: '2'
    EU: '2'
    HK: '3'
    TW: '3'
    JP: '4'
    KR: '5'
    OT: '6'