url: https://pt.msg.vg
host: msg.vg
siteType: NexusPHP
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAMAAABhq6zVAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAeFBMVEWGw/6Hw/6HxP6Fw/6Lxv6r1f6Xy/6s1v6h0f6g0P6Tyv6fz/6i0f6ez/6Lxf632/6l0v6p1P6x2P6n0/6n1P6RyP6j0f6Nxv6Vyv6j0v6w2P6f0P6h0P673f663f6Ryf6Px/6Kxf6azf6QyP6YzP6Uyv6Fwv7///+R5Vm0AAAAAWJLR0QnLQ+oIwAAAAd0SU1FB+YCAQQLEUD4N98AAABPSURBVAjXlc3XEYAgAAXBRxAUEQUDmLP9lygl6P7fHPAHASgDeMKFTDOV64LAlJV1VtdN23kE6fphnGaplxV+M7sSxxmumwKxY+xh0dfbCwB/A5hH0DsvAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTAyLTAxVDA0OjExOjE1KzAwOjAwiHfJQwAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wMi0wMVQwNDoxMToxNyswMDowMG61YNYAAAAASUVORK5CYII=
asSource: true
asTarget: true
seedDomSelector: '#top~table:first>tbody>tr:nth-child(3)'
uploadPath: /upload.php
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
  result: 
    list: '.torrents>tbody>tr'
    url: '.torrentname td a[href*="details.php?id="]'
    name: '.torrentname td a[href*="details.php?id="]'
    size: 'td:nth-child(5)'
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
anonymous: 
  selector: 'input[name="uplver"]'
category:
  selector: '#browsecat'
  map:
    movie: '401'
    tv: '402'
    tvPack: '402'
    documentary: '404'
    concert: '406'
    sport: '407'
    cartoon: '405'
    variety: '403'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '1'
    x264: '1'
    hevc: '18'
    x265: '18'
    h265: '18'
    mpeg2: '4'
    mpeg4: '17'
    vc1: '2'
    xvid: '3'
    dvd: '4'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '1'
    bluray: '1'
    remux: '3'
    encode: '7'
    web: '10'
    hdtv: '5'
    dvd: '6'
    dvdrip: '6'
    hddvd: '2'
    other: '11'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    2160p: '6'
    1080p: '1'
    1080i: '2'
    720p: '3'
    576p: '4'
    480p: '4'
team: 
  selector: 'select[name="team_sel"]'
  map:
    hds: '1'
    chd: '2'
    mysilu: '3'
    wiki: '4'
    other: '5'
    ptmsg: '6'