url: 'https://springsunday.net'
host: springsunday.net
siteType: NexusPHP
asSource: true
asTarget: true
uploadPath: /upload.new.php
seedDomSelector: '#top~table:first>tbody>tr:nth-child(3)'
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
name:
  selector: '#name'
subtitle:
  selector: '#small_descr'
description:
  selector: '#descr'
poster: '#url_poster'
imdb:
  selector: '#url'
anonymous: 
  selector: 'input[name="uplver"]'
mediaInfo:
  selector: '#Media_BDInfo'
screenshots:
  selector: '#url_vimages'
category:
  selector: '#browsecat'
  map:
    movie: '501'
    tv: '502'
    tvPack: '502'
    documentary: '503'
    concert: '507'
    sport: '506'
    cartoon: '504'
    variety: '505'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '2'
    hevc: '1'
    x264: '2'
    x265: '1'
    h265: '1'
    mpeg2: '4'  
    mpeg4: '2'
    vc1: '3'
    xvid: ''
    dvd: '4'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '5'
    ac3: '4'
    dd: '4'
    dd+: '4'
    flac: '7'
    dts: '3'  
    truehd: '2'
    lpcm: '6'
    dtshdma: '1'
    atmos: '3'
    dtsx: '3'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '1'
    bluray: '1'
    remux: '4'
    encode: '6'
    web: '7'
    hdtv: '5'
    dvd: '3'
    dvdrip: '10'
    other: ''
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    2160p: '1'
    1080p: '2'
    1080i: '3'
    720p: '4'
    576p: '5'
    480p: '5'
area:
  selector: 'select[name="source_sel"]'
  map:
    CN: '1'
    US: '9'
    EU: '9'
    HK: '2'
    TW: '2'
    JP: '10'
    KR: '10'
    OT: '3'