url: https://totheglory.im
host: totheglory.im
siteType: TTG
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH5woaCC40liGC4QAAA+FJREFUOMttlEtTVEccxX+3+5K5wzyAASKPMaLRLCAp3fhKstG8voRV2eXb+CHMB4hJ9mZhrIpVwZTCiEYepgYYYAZl7ozcV7+yuDBClV3V1b06fc7/nNPenTt37n566dL5YjEYy7LEWuNwzmGtxVpLkiSE3ZA0TdFaY63FGIPWGmMMxhiUUhhjAPA/v7ww/82tby9OT03XtNbW4cABgBCC3d0dHv/1mNbODlppjM3BlFKD8/junMOvVivVs/X6xJkzU6N8YAVBQON5A7ErEEKAB9ZahBB4nvd+4+Gw+HEcJf13PV2r1fA8ge/7AGRZhtaKdmePbrdL2OthjiRrc3QeM8xyhtYZ/O7bLq9fr+OcpTY2zvj4JADd7lt2drZZX9/gXb+PFB5OCJxzOMcpuceSjTX4B297/PPkGe29N8zPz1OrTeB5kKQJ3bAHnmB+YQGjDc5ZrHO02x0ayw0ODw/JlMJoPTDMV0oRxzFRFJNl6mhyHpMTHzM8XEYrjZACj9wrKSRra6tsbjZptVqkaYZz9j1gHo88KidXsThMsTj8IZ8IwxCVKcKwh9IZzoEzFiFFDqhPUAZwOHq9kDTJCIKAarUKDrrhAb1ej/X1NYJiwKXPLiKlIEkS9vbavNl/g38ypAOWDl68XGF7a5uz9U+4evUaOFhuLPFkcZEsU9y4eYOz9TqlUolOp8ODB3/w26+/42utjyKiT0nf2+2wtrqBL4aO3rDs7+8zXC5xdf4Lrly+wtDQEEIIpqamaTabSClzyc45+v0+GxvrBEEBay2rq6uEvRDw8qh4sLAwD3jMTM9SKpUGeY2iiHeHh8RxnDME6Pf7rDxfodlsopSi2WwyMjKClDKvoSc4d+48vvSR0idNU1ZePGd5aZl2p83Ll/+SpmkOaIwhiRP6/T7xf/Hg1UKhAB6DahU+CoC8ent7O9y//wutnRblUoVyucz169dyU5RSeF4uTUqJ7/s45zDGcDwSz/MGsUmzlK2tLZ49fcr3P3zHrdu3CYIivbCXMzwGVFqdqlOSJERRRJZlSCmQ0kcIgZSScqXC9MwU9foss9N1yuUqZtYgL1y48GMQBGestcNpmp7qplKKg4MDXr16xaNHf6KNYmxslFKpTCEIqNVGmZwcZ3RkjFKpnKs7KfkkGOTONxoNlpaWiKKIza1NCoWAr778mtGRUa5fu0mcRARBcTAO3xgjtdae53mDxuSgZiA773rEw4ePqNVqlMsl5s6dp1yuUCpVMMbQ7rTZ3t5Czs3N/RQEwQRQHHxDJ9pzXEcpJd0wpLXdIo4iZmZnqFSqSF8SxxGLi39z7+d7/A+iMsWK5Inr3gAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMy0xMC0yNlQwODo0Njo1MiswMDowMO+VxjIAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjMtMTAtMjZUMDg6NDY6NTIrMDA6MDCeyH6OAAAAKHRFWHRkYXRlOnRpbWVzdGFtcAAyMDIzLTEwLTI2VDA4OjQ2OjUyKzAwOjAwyd1fUQAAAABJRU5ErkJggg==
asSource: true
asTarget: true
seedDomSelector: '#main_table h1~table:first>tbody>tr:nth-child(2)'
torrentDownloadLinkSelector: 'a[href*="im/dl/"]'
uploadPath: /upload.php
search:
  path: /browse.php
  replaceKey:
    - tt
    - imdb
  params:
    search_field: '{imdb}'
    sort: '5'
    type: desc
    c: M
  result:
    list: '#torrent_table>tbody>tr'
    url: .name_left a[href*="/t/"]
    name: .name_left a[href*="/t/"] b
    size: td:nth-child(7)
name:
  selector: input[name="name"]
subtitle:
  selector: input[name="subtitle"]
description:
  selector: textarea[name="descr"]
imdb:
  selector: input[name="imdb_c"]
anonymous:
  selector: select[name="anonymity"]
  value: yes
torrent:
  selector: 'input[name="file"]'
category:
  selector: select[name="type"]
  map:
    movie:
      - '51'
      - '52'
      - '53'
      - '54'
      - '108'
      - '109'
    tv:
      - '69'
      - '70'
      - '73'
      - '74'
      - '75'
      - '76'
    tvPack:
      - '87'
      - '88'
      - '99'
      - '90'
    documentary:
      - '62'
      - '63'
      - '67'
    concert: '59'
    sport: '57'
    cartoon: '58'
    music: '83'
    variety:
      - '103'
      - '60'
      - '101'
videoType:
  map:
    uhdbluray:
      - '109'
    bluray:
      - '54'
      - '109'
      - '67'
    remux:
      - '53'
      - '108'
      - '63'
      - '70'
      - '75'
    encode:
      - '53'
      - '63'
      - '70'
      - '75'
      - '52'
      - '62'
      - '69'
      - '76'
      - '108'
    web:
      - '53'
      - '62'
      - '63'
      - '70'
      - '75'
      - '52'
      - '69'
      - '76'
      - '108'
      - '87'
      - '88'
      - '99'
      - '90'
    hdtv:
      - '53'
      - '63'
      - '70'
      - '75'
      - '52'
      - '62'
      - '69'
      - '76'
      - '108'
      - '87'
      - '88'
      - '99'
      - '90'
    dvd:
      - '51'
    dvdrip:
      - '51'
    other: ''
resolution:
  map:
    2160p:
      - '108'
      - '109'
      - '67'
    1080p:
      - '53'
      - '63'
      - '70'
      - '75'
      - '54'
      - '67'
      - '87'
      - '88'
      - '99'
      - '90'
    1080i:
      - '53'
      - '63'
      - '70'
      - '75'
      - '87'
      - '88'
      - '99'
      - '90'
    720p:
      - '52'
      - '62'
      - '69'
      - '76'
      - '87'
      - '88'
      - '99'
      - '90'
    576p: '51'
    480p: '51'
area:
  map:
    CN:
      - '76'
      - '75'
      - '90'
    US:
      - '69'
      - '70'
      - '87'
    EU:
      - '69'
      - '70'
      - '87'
    HK:
      - '76'
      - '75'
      - '90'
    TW:
      - '76'
      - '75'
      - '90'
    JP:
      - '73'
      - '88'
      - '101'
    KR:
      - '74'
      - '99'
      - '103'
    OT: ''
