name: script build
on:
  push:
    paths:
      - 'src/**'
      - 'scripts/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'src/**'
      - 'scripts/**'
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
           node-version: '14'
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: easy-upload.user.js
          path: dist
